<ul class="breadcrumb">
    <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
			<i class="icon-home"></i>
			<a href="#">Home</a>
			<span class="divider">
				<i class="icon-angle-right"></i>
			</span>
		</li>
		<li class="active">
            <?php
            // if this isn't the last page, add a link and the separator
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
            <?php // otherwise, just output the name
            else:
            ?>
               <?php echo $page->getLabel(); ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
</ul>
