					<div class="page-header position-relative">
						<h1>
							Form Elements
							<small>
								<i class="icon-double-angle-right"></i>
								Common form elements and layouts
							</small>
						</h1>
					</div><!--/.page-header-->

					<div class="row-fluid">
						<!--PAGE CONTENT BEGINS HERE-->

						<form class="form-horizontal">
							<div class="control-group">
								<label class="control-label" for="form-field-1">站点名称</label>
								<div class="controls">
									<input type="text" id="form-field-1" placeholder="站点名称">
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-2">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-2" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-3">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-3" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-4">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-4" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-5">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-5" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-6">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-6" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-2">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-2" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-2">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-2" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="form-field-2">站点URL</label>
								<div class="controls">
									<input type="password" id="form-field-2" placeholder="站点URL">
									<span class="help-inline">Example:http://www.baidu.com</span>
								</div>
							</div>

							<div class="form-actions">
								<button class="btn btn-info" type="submit">
									<i class="icon-ok bigger-110"></i>
									Submit
								</button>
								&nbsp; &nbsp; &nbsp;
								<button class="btn" type="reset">
									<i class="icon-undo bigger-110"></i>
									Reset
								</button>
							</div>

							<div class="hr"></div>
						</div>
						<!--PAGE CONTENT ENDS HERE-->
					</div><!--/row-->

